- ks46team04/src/main/resources/.gitignore
file: ignore
detail:	application.properties - ignore file
> author:LBR

- ks46team04/src/main/resources/templates/view/goods/add_goods.html
- ks46team04/src/main/resources/templates/view/goods/goods_list.html
author: 김귀림
file: add_goods.html, goods_list.html
detail: add_goods.html, goods_list.html 코드 수정
> [ksmart46team04] goods html 코드 수정

- ks46team04/src/main/java/ks46team04/admin/controller/FoundationController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FoundationMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/FoundationService.java
- ks46team04/src/main/resources/.gitignore
- ks46team04/src/main/resources/mapper/FoundationMapper.xml
- ks46team04/src/main/resources/templates/view/foundation/add_foundation.html
- ks46team04/src/main/resources/templates/view/foundation/foundation_list.html
author: 김귀림
file: add_foundation.html, foundation_list.html,
FoundationController.java, FoundationMapper.java, FoundationMapper.xml, FoundatonService.java
detail: add_foundation.html, foundation_list.html, FoundationController.java, FoundationMapper.java, FoundatonService.java
- 코드 수정,  FoundationMapper.xml - 파일 추가
> [ksmart46team04] foundation html, Controller, Mapper, Service 수정

- ks46team04/src/main/java/ks46team04/admin/controller/FoundationController.java
- ks46team04/src/main/java/ks46team04/admin/controller/GoodsController.java
- ks46team04/src/main/resources/templates/fragments/aside.html
author: 김귀림
file: aside.html, FoundationController.java, GoodsController.java
detail: view -> admin으로 경로 수정, aside admin 경로 추가
> [ksmart46team04] aside, controller 경로 수정(goods, foundation)

- ks46team04/src/main/java/ks46team04/admin/controller/DonationController.java
- ks46team04/src/main/java/ks46team04/admin/dto/Donation.java
- ks46team04/src/main/java/ks46team04/admin/mapper/DonationMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/DonationService.java
- ks46team04/src/main/resources/mapper/DonationMapper.xml
- ks46team04/src/main/resources/templates/fragments/aside.html
author: 백지은
file: donationCotroller.java, donationService.java, donationMapper.java, donationMapper.java.xml, donation.java, aside.html detail: 정기기부 컨트롤러/서비스/매퍼/dto 추가, aside 화면 연결
> [ksmart46team04] 정기기부 수정

- ks46team04/src/main/resources/static/css/style.css
- ks46team04/src/main/resources/templates/funding_index.html
author: 고현지
file: funding_index.html, style.css
detail: funding_index 수정
> [KHJ] funding_index 수정

- ks46team04/src/main/java/ks46team04/admin/controller/UserController.java
- ks46team04/src/main/resources/mapper/UserMapper.xml
- ks46team04/src/main/resources/templates/admin/user/activityStatus.html
- ks46team04/src/main/resources/templates/admin/user/loginLog.html
author: 김가람
file: loginLog.html
detail:loginLog.html 수정
> [ksmart46team04]

- ks46team04/src/main/java/ks46team04/admin/controller/DonationController.java
- ks46team04/src/main/resources/templates/admin/donation/donationRefund_add.html
- ks46team04/src/main/resources/templates/admin/donation/donationRefund_list.html
- ks46team04/src/main/resources/templates/admin/donation/donationRefund_modify.html
- ks46team04/src/main/resources/templates/admin/donation/donationSub_list.html
- ks46team04/src/main/resources/templates/fragments/aside.html
author: LBR
detail: 아래 파일 추가 및 컨트롤러 화면 연결
donationRefund_add - 환불 신청, 하나의 결제건에 대해서만 환불 신청
donationRefund_list 환불조회
donationRefund_modify 환불 수정
donationSub_list - 회원 정기기부 구독 조회
file: ks46team04/src/main/resources/templates/fragments/aside.html ks46team04/src/main/java/ks46team04/admin/controller/DonationController.java ks46team04/src/main/resources/templates/admin/donation/donationRefund_add.html ks46team04/src/main/resources/templates/admin/donation/donationRefund_list.html ks46team04/src/main/resources/templates/admin/donation/donationRefund_modify.html ks46team04/src/main/resources/templates/admin/donation/donationSub_list.html
> [ks46team4] donation 초안 파일4개 추가

- ks46team04/src/main/java/ks46team04/common/controller/CommonController.java
- ks46team04/src/main/resources/static/css/admin_khj.css
- ks46team04/src/main/resources/static/css/sb-admin-2.min.css
- ks46team04/src/main/resources/static/js/custom/khj.js
- ks46team04/src/main/resources/templates/admin/funding/manage.html
- ks46team04/src/main/resources/templates/admin/funding/modifyFunding.html
- ks46team04/src/main/resources/templates/common/funding_detail2.html
- ks46team04/src/main/resources/templates/common/funding_detail3.html
author: 고현지
file:
CommonController.java
manage.html
modifyFunding.html
funding_detail.html
funding_detail2.html
funding_detail3.html
sb-admin-2.min.css
khj.js
admin_khj.css
detail:
펀딩상세페이지2, 3 생성
어드민>펀딩수정 페이지 수정
어드민>펀딩목록 페이지 수정기능 수정
메인페이지 css 수정
> [KHJ] 펀딩페이지 수정

- ks46team04/src/main/java/ks46team04/admin/controller/PurchaseController.java
- ks46team04/src/main/java/ks46team04/admin/controller/VatController.java
- ks46team04/src/main/java/ks46team04/admin/dto/Purchase.java
- ks46team04/src/main/java/ks46team04/admin/dto/Vat.java
- ks46team04/src/main/java/ks46team04/admin/mapper/PurchaseMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/VatMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/PurchaseService.java
- ks46team04/src/main/java/ks46team04/admin/service/VatService.java
- ks46team04/src/main/resources/mapper/PurchaseMapper.xml
- ks46team04/src/main/resources/mapper/VatMapper.xml
- ks46team04/src/main/resources/templates/admin/purchase_sale/payment_vat_list.html
- ks46team04/src/main/resources/templates/common/funding_index.html
author: LBR
detail: vat 조회 완료, purchase 작업중
file:
ks46team04/src/main/java/ks46team04/admin/dto/Purchase.java ks46team04/src/main/java/ks46team04/admin/controller/PurchaseController.java ks46team04/src/main/java/ks46team04/admin/mapper/PurchaseMapper.java ks46team04/src/main/resources/mapper/PurchaseMapper.xml ks46team04/src/main/java/ks46team04/admin/service/PurchaseService.java ks46team04/src/main/java/ks46team04/admin/dto/Vat.java ks46team04/src/main/java/ks46team04/admin/controller/VatController.java ks46team04/src/main/java/ks46team04/admin/mapper/VatMapper.java ks46team04/src/main/resources/mapper/VatMapper.xml ks46team04/src/main/java/ks46team04/admin/service/VatService.java
> [ks46team4] 하루 종료 develop

- ks46team04/src/main/java/ks46team04/admin/controller/UserController.java
- ks46team04/src/main/resources/mapper/UserMapper.xml
- ks46team04/src/main/resources/templates/admin/user/activityStatus.html
- ks46team04/src/main/resources/templates/admin/user/modifyUser.html
- ks46team04/src/main/resources/templates/admin/user/removeUser.html
- ks46team04/src/main/resources/templates/admin/user/userList.html
author:김가람
file:activityStatus.html
modifyUser.html
removeUser.html
userList.html
UserMapper.xml
> [ksmart46team04]화면 수정

- ks46team04/src/main/java/ks46team04/admin/controller/FoundationController.java
- ks46team04/src/main/java/ks46team04/admin/controller/StockController.java
- ks46team04/src/main/java/ks46team04/admin/dto/FoundationRequest.java
- ks46team04/src/main/java/ks46team04/admin/dto/Stock.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FoundationMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/GoodsMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/StockMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/FoundationService.java
- ks46team04/src/main/java/ks46team04/admin/service/StockService.java
- ks46team04/src/main/resources/mapper/FoundationMapper.xml
- ks46team04/src/main/resources/mapper/StockMapper.xml
- ks46team04/src/main/resources/static/css/sb-admin-2.min.css
- ks46team04/src/main/resources/templates/admin/foundation/add_foundation.html
- ks46team04/src/main/resources/templates/admin/foundation/add_foundation_request.html
- ks46team04/src/main/resources/templates/admin/foundation/foundation_list.html
- ks46team04/src/main/resources/templates/admin/foundation/foundation_request_list.html
- ks46team04/src/main/resources/templates/admin/goods/add_goods.html
- ks46team04/src/main/resources/templates/admin/goods/goods_list.html
- ks46team04/src/main/resources/templates/admin/goods/remove_goods.html
- ks46team04/src/main/resources/templates/admin/stock/stock_list.html
author: 김귀림
file: sb-admin-2.min.css, goods/foundation/stock 관련 파일 detail: table white space 관련 css 추가, goods/foundation/stock 관련 파일 추가 및 수정
> [ksmart46team04] css table관련 코드 추가, goods,foundation,stock 수정

- ks46team04/src/main/java/ks46team04/admin/controller/ProfitLossController.java
- ks46team04/src/main/java/ks46team04/admin/controller/PurchaseController.java
- ks46team04/src/main/java/ks46team04/admin/controller/SaleController.java
- ks46team04/src/main/java/ks46team04/admin/dto/ProfitLoss.java
- ks46team04/src/main/java/ks46team04/admin/dto/Purchase.java
- ks46team04/src/main/java/ks46team04/admin/dto/TotalPurchaseSale.java
- ks46team04/src/main/java/ks46team04/admin/dto/UnionDonaFund.java
- ks46team04/src/main/java/ks46team04/admin/mapper/ProfitLossMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/SaleMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/ProfitLossService.java
- ks46team04/src/main/java/ks46team04/admin/service/PurchaseService.java
- ks46team04/src/main/java/ks46team04/admin/service/SaleService.java
- ks46team04/src/main/resources/mapper/ProfitLossMapper.xml
- ks46team04/src/main/resources/mapper/PurchaseMapper.xml
- ks46team04/src/main/resources/mapper/SaleMapper.xml
- ks46team04/src/main/resources/templates/admin/purchase_sale/month_profit_loss.html
- ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_list.html
- ks46team04/src/main/resources/templates/admin/purchase_sale/sales_list.html
author: LBR
detail: 수수료, 매입, 매출, 매입매출 종합 및 손익
file:
ks46team04/src/main/resources/templates/admin/purchase_sale/month_profit_loss.html ks46team04/src/main/java/ks46team04/admin/dto/ProfitLoss.java ks46team04/src/main/java/ks46team04/admin/controller/ProfitLossController.java ks46team04/src/main/java/ks46team04/admin/mapper/ProfitLossMapper.java ks46team04/src/main/resources/mapper/ProfitLossMapper.xml ks46team04/src/main/java/ks46team04/admin/service/ProfitLossService.java ks46team04/src/main/java/ks46team04/admin/dto/Purchase.java ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_list.html ks46team04/src/main/java/ks46team04/admin/controller/PurchaseController.java ks46team04/src/main/java/ks46team04/admin/mapper/PurchaseMapper.java …
> [ks46team4] 관리 페이지 재무 관련 기본 조회 연결 완료

- ks46team04/src/main/java/ks46team04/admin/controller/FundingController.java
- ks46team04/src/main/java/ks46team04/admin/dto/FoundationName.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FundingMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/FundingService.java
- ks46team04/src/main/resources/mapper/FundingMapper.xml
- ks46team04/src/main/resources/static/css/admin_khj.css
- ks46team04/src/main/resources/static/js/custom/khj.js
- ks46team04/src/main/resources/templates/admin/funding/manage.html
- ks46team04/src/main/resources/templates/admin/funding/modifyFunding.html
- ks46team04/src/main/resources/templates/admin/funding/search.html
author: KHJ
file:
manage.html,
admin_khj.css,
khj.js,
search.html,
FoundationName.java
detail: 펀딩관리페이지 검색 기능, 펀딩 수정화면 수정 중...
> [KHJ] 펀딩관리페이지 수정

- ks46team04/src/main/java/ks46team04/admin/controller/FundingController.java
- ks46team04/src/main/java/ks46team04/admin/dto/FundingFoundation.java
- ks46team04/src/main/java/ks46team04/admin/dto/GoodsCode.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FundingMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/FundingService.java
- ks46team04/src/main/resources/mapper/FundingMapper.xml
- ks46team04/src/main/resources/templates/admin/funding/manage.html
- ks46team04/src/main/resources/templates/admin/funding/modifyFunding.html
- ks46team04/src/main/resources/templates/admin/funding/payments.html
- ks46team04/src/main/resources/templates/admin/funding/refund.html
- ks46team04/src/main/resources/templates/admin/funding/register.html
author: KHJ
file:
FundingFoundation.java,
GoodsCode,
manage.html,
payments.html,
refund.html,
register.html
detail: 펀딩관련 어드민 페이지 수정, dto 2개 생성
> [KHJ] 펀딩관련 어드민 페이지 수정

- ks46team04/src/main/resources/logback-spring.xml
- ks46team04/src/main/resources/static/js/custom/khj.js
author: khj
file: logback-spring.xml
detail: log file 출력 및 file 경로 셋팅
> [ksmart46team04] logback 수정

- ks46team04/src/main/java/ks46team04/admin/controller/FundingController.java
- ks46team04/src/main/resources/templates/admin/funding/current_amount.html
- ks46team04/src/main/resources/templates/admin/funding/manage.html
- ks46team04/src/main/resources/templates/admin/funding/modifyFunding.html
- ks46team04/src/main/resources/templates/admin/funding/payments.html
- ks46team04/src/main/resources/templates/admin/funding/register.html
- ks46team04/src/main/resources/templates/fragments/aside.html
author: 고현지
file:
aside.html,
current_amount.html,
manage.html,
payments.html,
register.html
detail: 어드민페이지 펀딩 메뉴 펼침 오류 해결, 펀딩관련 어드민 페이지 수정
> [ksmart46team04] 어드민 asdie.html 수정, 펀딩관련 어드민 페이지 수정

- ks46team04/src/main/java/ks46team04/admin/controller/FundingController.java
- ks46team04/src/main/java/ks46team04/admin/dto/FundingPay.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FundingMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/FundingService.java
- ks46team04/src/main/resources/mapper/FundingMapper.xml
- ks46team04/src/main/resources/static/css/admin_khj.css
- ks46team04/src/main/resources/templates/admin/funding/manage.html
- ks46team04/src/main/resources/templates/admin/funding/modifyFunding.html
- ks46team04/src/main/resources/templates/admin/funding/modifyFundingPay.html
- ks46team04/src/main/resources/templates/admin/funding/payments.html
- ks46team04/src/main/resources/templates/fragments/aside.html
author: 고현지
file:
admin_khj.css,
aside.html,
FundingPay.java,
manage.html,
modifyFunding.java,
modifyFundingPay.html,
payments.html
detail: fundingPay dto 생성, 펀딩등록 페이지 수정, 펀딩 결제기록 조회 페이지 수정, aside 펀딩 관련 페이지 경로 수정
> [ksmart46team04] 펀딩관련 페이지 수정 및 생성, 어드민 aside 경로 수정

- ks46team04/src/main/java/ks46team04/admin/controller/DonationController.java
- ks46team04/src/main/java/ks46team04/admin/dto/DonationPayDetail.java
- ks46team04/src/main/java/ks46team04/admin/dto/DonationPayMethod.java
- ks46team04/src/main/java/ks46team04/admin/dto/DonationSub.java
- ks46team04/src/main/java/ks46team04/admin/mapper/DonationMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/DonationService.java
- ks46team04/src/main/resources/mapper/DonationMapper.xml
- ks46team04/src/main/resources/templates/admin/donation/donationPayDetail_list.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayMethod_add.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayMethod_list.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayMethod_modify.html
- ks46team04/src/main/resources/templates/admin/donation/donationSub_add.html
- ks46team04/src/main/resources/templates/admin/donation/donationSub_list.html
- ks46team04/src/main/resources/templates/admin/donation/donationSub_modify.html
- ks46team04/src/main/resources/templates/admin/donation/donation_modify.html
- ks46team04/src/main/resources/templates/fragments/aside.html
author: 백지은
file: donation 관련 컨트롤, 서비스, 매퍼, html
detail: 정기기부 파일 추가, 수정
> [ksmart46team04] 정기기부 파일 추가, 수정

- ks46team04/src/main/java/ks46team04/admin/controller/GoodsController.java
- ks46team04/src/main/java/ks46team04/admin/dto/Goods.java
- ks46team04/src/main/java/ks46team04/admin/dto/GoodsCategory.java
- ks46team04/src/main/java/ks46team04/admin/mapper/GoodsMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/GoodsService.java
- ks46team04/src/main/resources/mapper/GoodsMapper.xml
- ks46team04/src/main/resources/static/js/custom/kgr9.js
- ks46team04/src/main/resources/templates/admin/foundation/foundation_list.html
- ks46team04/src/main/resources/templates/admin/foundation/foundation_request_list.html
- ks46team04/src/main/resources/templates/admin/goods/add_goods.html
- ks46team04/src/main/resources/templates/admin/goods/goods_list.html
- ks46team04/src/main/resources/templates/admin/goods/modify_goods.html
- ks46team04/src/main/resources/templates/admin/stock/in_outcoming_list.html
- ks46team04/src/main/resources/templates/admin/stock/unusual_stock_detail_list.html
author: 김귀림
file: kgr9.js, goods/foundation/stock/unusual stock 관련 파일
detail: kgr9.js 추가, goods/foundation/stock/unusual stock 관련 파일 수정
> [ksmart46team04] js 개인파일 추가, goods/foundation/stock/unusual stock 관련 수정

- ks46team04/src/main/java/ks46team04/admin/controller/FundingController.java
- ks46team04/src/main/java/ks46team04/admin/dto/FundingRefund.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FundingMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/FundingService.java
- ks46team04/src/main/resources/mapper/FundingMapper.xml
- ks46team04/src/main/resources/static/css/admin_khj.css
- ks46team04/src/main/resources/static/js/custom/khj.js
- ks46team04/src/main/resources/templates/admin/funding/manage.html
- ks46team04/src/main/resources/templates/admin/funding/payments.html
- ks46team04/src/main/resources/templates/admin/funding/refund.html
author: KHJ
file:
khj.js
admin_khj.css
refund.html
manage.html
payments.html
FundingMapper.xml
FundingRefund.java
FundingController.java
FundingService.java
detail: 펀딩관련 페이지 수정, 환불페이지 검색기능 일부 추가, 펀딩 수정 페이지 수정일자 및 등록일자 수정
> [ksmart46] 펀딩관련 페이지 수정

- ks46team04/src/main/resources/templates/admin/funding/modifyFunding.html
- ks46team04/src/main/resources/templates/admin/funding/modifyFundingPay.html
- ks46team04/src/main/resources/templates/admin/funding/register.html
author: 고현지
file:
modifyFundingPay.html,
register.html
detail: 펀딩 수정 페이지, 펀딩 결제내역 상세페이지, 펀딩 등록페이지
> [ksmart46] 어드민 펀딩 관련 페이지 수정

- ks46team04/src/main/resources/mapper/GoodsMapper.xml
- ks46team04/src/main/resources/static/js/custom/kgr9.js
- ks46team04/src/main/resources/templates/admin/foundation/foundation_list.html
- ks46team04/src/main/resources/templates/admin/foundation/foundation_request_list.html
- ks46team04/src/main/resources/templates/admin/goods/add_goods.html
- ks46team04/src/main/resources/templates/admin/goods/goods_list.html
- ks46team04/src/main/resources/templates/admin/stock/in_outcoming_list.html
- ks46team04/src/main/resources/templates/admin/stock/outcoming_detail_list.html
- ks46team04/src/main/resources/templates/admin/stock/stock_list.html
- ks46team04/src/main/resources/templates/admin/stock/unusual_stock_detail_list.html
author: 김귀림
file: goods_list.html,foundation_list.html,foundation_request_list.html,in_outcoming_list.html,outcoming_detail_list.html,stock_list.html,unusual_stock_detail_list.html
detail: goods/foundation/stock/unusual stock html 조회 조건 수정
> [ksmart46team04] goods/foundation/stock/unusual stock html 조회 수정

- ks46team04/src/main/java/ks46team04/admin/controller/DonationController.java
- ks46team04/src/main/java/ks46team04/admin/dto/DonationMonthPay.java
- ks46team04/src/main/java/ks46team04/admin/mapper/DonationMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/DonationService.java
- ks46team04/src/main/resources/mapper/DonationMapper.xml
- ks46team04/src/main/resources/templates/admin/donation/donationMonthPay_add.html
- ks46team04/src/main/resources/templates/admin/donation/donationMonthPay_list.html
- ks46team04/src/main/resources/templates/admin/donation/donationMonthPay_modify.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayDetail_add.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayDetail_modify.html
- ks46team04/src/main/resources/templates/fragments/aside.html
author: 백지은
file: aside.html
정기기부 컨트롤러, 서비스, 매퍼 추가
donationPayDetail list, add, modify.html 추가
donationMonthPay list, add, modify.html 추가
detail: 정기기부 수정, 추가
> [ksmart46team04] aside 수정, 정기기부 수정/추가

- ks46team04/src/main/java/ks46team04/admin/controller/VatController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/VatMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/VatService.java
- ks46team04/src/main/resources/mapper/VatMapper.xml
- ks46team04/src/main/resources/templates/admin/purchase_sale/payment_vat_list.html
- ks46team04/src/main/resources/templates/admin/purchase_sale/payment_vat_update.html
- ks46team04/src/main/resources/templates/common/funding_index.html
- ks46team04/src/main/resources/templates/fragments/aside.html
author: LBR
detail: 수수료 조회, 조회->업데이트 모달, 수수료 업데이트 완료
file:
ks46team04/src/main/resources/templates/fragments/aside.html ks46team04/src/main/resources/templates/common/funding_index.html ks46team04/src/main/resources/templates/admin/purchase_sale/payment_vat_list.html ks46team04/src/main/resources/templates/admin/purchase_sale/payment_vat_update.html ks46team04/src/main/java/ks46team04/admin/controller/VatController.java ks46team04/src/main/java/ks46team04/admin/mapper/VatMapper.java ks46team04/src/main/resources/mapper/VatMapper.xml ks46team04/src/main/java/ks46team04/admin/service/VatService.java
> [ks46team4] 수수료 관리 기능 완료

- ks46team04/src/main/java/ks46team04/admin/controller/FundingController.java
- ks46team04/src/main/java/ks46team04/admin/dto/FundingRefund.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FundingMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/FundingService.java
- ks46team04/src/main/resources/mapper/FundingMapper.xml
- ks46team04/src/main/resources/static/css/admin_khj.css
- ks46team04/src/main/resources/static/js/custom/khj.js
- ks46team04/src/main/resources/templates/admin/funding/manage.html
- ks46team04/src/main/resources/templates/admin/funding/modifyFunding.html
- ks46team04/src/main/resources/templates/admin/funding/modifyFundingPay.html
- ks46team04/src/main/resources/templates/admin/funding/modifyFundingRefund.html
- ks46team04/src/main/resources/templates/admin/funding/payments.html
- ks46team04/src/main/resources/templates/admin/funding/refund.html
- ks46team04/src/main/resources/templates/common/funding_index.html
author: KHJ
file:
admin_khj.css,
khj.js,
funding_index.html,
FundingRefund.java,
manage.html,
modifyFundingPay.html,
modifyFundingRefund.html,
payments.html,
refund.html
detail:
펀딩환불관리 페이지> 목록 조회 데이터 잘못 보여지는 부분 수정
펀딩결제내역 페이지> 조회 데이터 정렬 수정, 금액 컬럼에 구분자와 기호 추가함
펀딩 상세 결제내역> 에러 있던 xml 쿼리문 수정, 페이지 연결 o
환불 상세내역 페이지 생성 및 연결
각 수정페이지 취소 버튼 자바스크립트 수정
> [ksmart46] 펀딩관련 어드민 페이지 수정, 메인인덱스 페이지 수정

- ks46team04/src/main/java/ks46team04/admin/controller/GoodsController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/GoodsMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/GoodsService.java
- ks46team04/src/main/resources/mapper/GoodsMapper.xml
- ks46team04/src/main/resources/static/css/admin_kgr9.css
- ks46team04/src/main/resources/static/js/custom/kgr9.js
- ks46team04/src/main/resources/templates/admin/goods/add_goods.html
- ks46team04/src/main/resources/templates/admin/goods/goods_list.html
- ks46team04/src/main/resources/templates/admin/goods/modify_goods.html
author: 김귀림
file: add_goods.html, modify_goods.html, goods 관련 controller, service, mapper
detail: goods(add, modify, remove) 관련 수정
> [ksmart46team04] goods(add, modify, remove) 관련 수정

- ks46team04/src/main/java/ks46team04/common/mapper/CommonMapper.java
- ks46team04/src/main/resources/mapper/CommonMapper.xml
author: LBR
detail: 공용 자동증가 코드 추가 CommonMapper.java, CommonMapper.xml file:
ks46team04/src/main/java/ks46team04/common/mapper/CommonMapper.java ks46team04/src/main/resources/mapper/CommonMapper.xml
> [ks46team4] 자동 증가 코드 추가

- ks46team04/src/main/java/ks46team04/admin/controller/UserController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/CommonMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/UserService.java
- ks46team04/src/main/resources/mapper/CommonMapper.xml
- ks46team04/src/main/resources/static/css/sb-admin-2.min.css
- ks46team04/src/main/resources/templates/admin/user/addUser.html
- ks46team04/src/main/resources/templates/common/register.html
author: LBR
detail: 관리자 회원 등록 html 수정, 아이디 중복 체크 기능 완료, commonMapper 경로 수정(새 패키지 생성) 
file:
ks46team04/src/main/resources/templates/admin/user/addUser.html ks46team04/src/main/java/ks46team04/admin/mapper/CommonMapper.java ks46team04/src/main/java/ks46team04/common/mapper/CommonMapper.java ks46team04/src/main/resources/mapper/CommonMapper.xml ks46team04/src/main/resources/templates/common/register.html ks46team04/src/main/resources/static/css/sb-admin-2.min.css ks46team04/src/main/java/ks46team04/admin/controller/UserController.java ks46team04/src/main/java/ks46team04/admin/service/UserService.java
> [ks46team4] 회원 등록 아이디 중복체크 완료

- ks46team04/src/main/resources/templates/common/funding_index.html
author: LBR
file: ks46team04/src/main/resources/templates/common/funding_index.html
detail: 메인 버전 정보 해당 일자로 수정
> [ks46team4] 메인 배포 버전 정보 수정

- ks46team04/src/main/java/ks46team04/admin/controller/UserController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/UserMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/UserService.java
- ks46team04/src/main/java/ks46team04/common/controller/CommonController.java
- ks46team04/src/main/resources/mapper/UserMapper.xml
- ks46team04/src/main/resources/templates/common/login.html
- ks46team04/src/main/resources/templates/fragments/header2.html
author: 김가람
file:
CommonController.java
header2.html
login.html
UserMapper.xml
> [ksmart46team04] 프로젝트 초기셋팅(로그인)

- ks46team04/src/main/resources/static/css/sb-admin-2.min.css
- ks46team04/src/main/resources/templates/admin/user/addUser.html
author: LBR
file: addUser.html, sb-admin-2.min.css
detail: 유저 등록 JS 완료, 제출 미완료
> [ks46team4] 유저 입력 양식 JS 완료

- ks46team04/src/main/java/ks46team04/admin/controller/UserController.java
- ks46team04/src/main/java/ks46team04/admin/service/UserService.java
- ks46team04/src/main/resources/mapper/UserMapper.xml
- ks46team04/src/main/resources/templates/admin/user/addUser.html
- ks46team04/src/main/resources/templates/admin/user/userList.html
- ks46team04/src/main/resources/templates/fragments/aside.html
author: LBR
detail: js 유효성 검사, submit, DB insert 등록까지 모두 완료
file:
ks46team04/src/main/resources/templates/admin/user/addUser.html ks46team04/src/main/resources/templates/fragments/aside.html ks46team04/src/main/java/ks46team04/admin/controller/UserController.java ks46team04/src/main/resources/templates/admin/user/userList.html ks46team04/src/main/resources/mapper/UserMapper.xml ks46team04/src/main/java/ks46team04/admin/service/UserService.java
> [ks46team4] addUser 완료

- ks46team04/src/main/java/ks46team04/admin/controller/GoodsController.java
- ks46team04/src/main/java/ks46team04/admin/controller/StockController.java
- ks46team04/src/main/java/ks46team04/admin/dto/Foundation.java
- ks46team04/src/main/java/ks46team04/admin/dto/FoundationRequest.java
- ks46team04/src/main/java/ks46team04/admin/dto/Goods.java
- ks46team04/src/main/java/ks46team04/admin/dto/InOutcoming.java
- ks46team04/src/main/java/ks46team04/admin/dto/OutcomingDetail.java
- ks46team04/src/main/java/ks46team04/admin/dto/Stock.java
- ks46team04/src/main/java/ks46team04/admin/mapper/GoodsMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/StockMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/GoodsService.java
- ks46team04/src/main/java/ks46team04/admin/service/StockService.java
- ks46team04/src/main/resources/mapper/FoundationMapper.xml
- ks46team04/src/main/resources/mapper/GoodsMapper.xml
- ks46team04/src/main/resources/mapper/StockMapper.xml
- ks46team04/src/main/resources/static/css/admin_kgr9.css
- ks46team04/src/main/resources/static/js/custom/kgr9.js
- ks46team04/src/main/resources/templates/admin/foundation/add_foundation.html
- ks46team04/src/main/resources/templates/admin/foundation/add_foundation_request.html
- ks46team04/src/main/resources/templates/admin/foundation/foundation_list.html
- ks46team04/src/main/resources/templates/admin/foundation/foundation_request_list.html
- ks46team04/src/main/resources/templates/admin/foundation/modify_foundation.html
- ks46team04/src/main/resources/templates/admin/foundation/modify_foundation_request.html
- ks46team04/src/main/resources/templates/admin/goods/add_goods.html
- ks46team04/src/main/resources/templates/admin/goods/goods_list.html
- ks46team04/src/main/resources/templates/admin/stock/modify_stock.html
- ks46team04/src/main/resources/templates/admin/stock/stock_list.html
- ks46team04/src/main/resources/templates/admin/stock/unusual_stock_detail_list.html
author: 김귀림
file: goods, foundation 관련 html, controller, service, mapper
detail:  goods, foundation remove 기능 수정
> [ksmart46team04] goods, foundation remove 기능 수정

- ks46team04/src/main/java/ks46team04/common/controller/CommonController.java
- ks46team04/src/main/resources/templates/common/login.html
- ks46team04/src/main/resources/templates/fragments/header2.html
author: LBR
detail: 동시 작업 파일 충돌 해결, header2, CommonController
file:
ks46team04/src/main/java/ks46team04/common/controller/CommonController.java ks46team04/src/main/resources/templates/fragments/header2.html ks46team04/src/main/resources/templates/common/login.html
> [ks46team4] 로그인 파일충돌 해결

- ks46team04/src/main/java/ks46team04/admin/controller/UserController.java
- ks46team04/src/main/resources/templates/admin/user/modifyUser.html
- ks46team04/src/main/resources/templates/fragments/header2.html
author: 김가람
file:
ks46team04/src/main/resources/templates/fragments/header2.html ks46team04/src/main/resources/templates/admin/user/modifyUser.html ks46team04/src/main/java/ks46team04/admin/controller/UserController.java
> [ksmart46team04] 로그인 충돌 해결

- ks46team04/src/main/java/ks46team04/admin/controller/FundingController.java
- ks46team04/src/main/java/ks46team04/admin/dto/FundingRefund.java
- ks46team04/src/main/java/ks46team04/admin/dto/RefundStatus.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FundingMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/FundingService.java
- ks46team04/src/main/resources/mapper/FundingMapper.xml
- ks46team04/src/main/resources/static/css/admin_khj.css
- ks46team04/src/main/resources/static/js/custom/khj.js
- ks46team04/src/main/resources/templates/admin/funding/current_amount.html
- ks46team04/src/main/resources/templates/admin/funding/manage.html
- ks46team04/src/main/resources/templates/admin/funding/modifyFunding.html
- ks46team04/src/main/resources/templates/admin/funding/modifyFundingRefund.html
- ks46team04/src/main/resources/templates/admin/funding/payments.html
- ks46team04/src/main/resources/templates/admin/funding/refund.html
author: KHJ
file:
admin_khj.css,
current_amount.html,
FoundationName.java,
FundingRefund.java,
khj.js,
manage.html,
modifyFundingRefund.html,
payments.html,
refund.html,
RefundStatus.java
detail:
manage 페이지 조회 목록에서 체크박스 선택된 펀딩 삭제 가능
FoundationName dto 삭제
체크박스 자바스크립트 코드 수정
RefundStatus dto 생성
> [ksmart46] 펀딩관리 페이지 삭제 기능

- ks46team04/src/main/java/ks46team04/admin/controller/PurchaseController.java
- ks46team04/src/main/java/ks46team04/user/controller/UserMainController.java
- ks46team04/src/main/resources/static/css/sb-admin-2.min.css
- ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_insert.html
- ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_list.html
- ks46team04/src/main/resources/templates/admin/user/addUser.html
author: LBR
detail: 매입 등록 화면 JS 완료, submit 정상
file:
ks46team04/src/main/resources/templates/admin/user/addUser.html ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_insert.html ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_list.html ks46team04/src/main/java/ks46team04/admin/controller/PurchaseController.java ks46team04/src/main/resources/static/css/sb-admin-2.min.css ks46team04/src/main/java/ks46team04/user/controller/UserMainController.java
> [ks46team4] 매입 등록 view 완료

- ks46team04/src/main/java/ks46team04/admin/controller/UserController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/UserMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/UserService.java
- ks46team04/src/main/resources/mapper/UserMapper.xml
- ks46team04/src/main/resources/templates/admin/user/modifyUser.html
- ks46team04/src/main/resources/templates/admin/user/removeUser.html
author: 김가람
file:
ks46team04/src/main/resources/templates/admin/user/modifyUser.html ks46team04/src/main/resources/templates/admin/user/removeUser.html ks46team04/src/main/java/ks46team04/admin/controller/UserController.java ks46team04/src/main/java/ks46team04/admin/mapper/UserMapper.java ks46team04/src/main/resources/mapper/UserMapper.xml ks46team04/src/main/java/ks46team04/admin/service/UserService.java
> [ksmart46team04] 프로젝트 초기셋팅(ex수정삭제)

- ks46team04/src/main/java/ks46team04/admin/controller/FoundationController.java
- ks46team04/src/main/java/ks46team04/admin/controller/GoodsController.java
- ks46team04/src/main/java/ks46team04/admin/controller/StockController.java
- ks46team04/src/main/java/ks46team04/admin/dto/InOutcoming.java
- ks46team04/src/main/java/ks46team04/admin/dto/OutcomingDetail.java
- ks46team04/src/main/java/ks46team04/admin/dto/UnusualStock.java
- ks46team04/src/main/java/ks46team04/admin/mapper/StockMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/GoodsService.java
- ks46team04/src/main/java/ks46team04/admin/service/StockService.java
- ks46team04/src/main/resources/mapper/FoundationMapper.xml
- ks46team04/src/main/resources/mapper/GoodsMapper.xml
- ks46team04/src/main/resources/mapper/StockMapper.xml
- ks46team04/src/main/resources/templates/admin/foundation/foundation_request_list.html
- ks46team04/src/main/resources/templates/admin/foundation/modify_foundation_request.html
- ks46team04/src/main/resources/templates/admin/goods/modify_goods.html
- ks46team04/src/main/resources/templates/admin/stock/in_outcoming_list.html
- ks46team04/src/main/resources/templates/admin/stock/modify_in_outcoming.html
- ks46team04/src/main/resources/templates/admin/stock/modify_stock.html
- ks46team04/src/main/resources/templates/admin/stock/outcoming_detail_list.html
- ks46team04/src/main/resources/templates/admin/stock/stock_list.html
- ks46team04/src/main/resources/templates/admin/stock/unusual_stock_detail_list.html
author: 김귀림
file: stock 관련 html, controller, service, mapper
detail: stock 조회, 수정 기능 관련 파일 수정
> [ksmart46team04] stock 관련 파일 수정

- ks46team04/src/main/java/ks46team04/admin/controller/FundingController.java
- ks46team04/src/main/java/ks46team04/admin/dto/FundingDetail.java
- ks46team04/src/main/java/ks46team04/admin/dto/FundingProduct.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FundingDetailMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FundingMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FundingProductMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/FundingProductService.java
- ks46team04/src/main/java/ks46team04/admin/service/FundingService.java
- ks46team04/src/main/java/ks46team04/common/controller/FundingDetailController.java
- ks46team04/src/main/java/ks46team04/common/controller/FundingListController.java
- ks46team04/src/main/resources/mapper/FundingDetailMapper.xml
- ks46team04/src/main/resources/mapper/FundingMapper.xml
- ks46team04/src/main/resources/mapper/FundingProduct.xml
- ks46team04/src/main/resources/static/css/admin_khj.css
- ks46team04/src/main/resources/static/css/style.css
- ks46team04/src/main/resources/templates/admin/funding/current_amount.html
- ks46team04/src/main/resources/templates/admin/funding/refund.html
- ks46team04/src/main/resources/templates/admin/funding/register.html
- ks46team04/src/main/resources/templates/common/funding/list.html
- ks46team04/src/main/resources/templates/common/funding1.html
- ks46team04/src/main/resources/templates/common/funding_detail.html
- ks46team04/src/main/resources/templates/fragments/header2.html
author: KHJ
file:
detail:
펀딩 진열 페이지 화면 연결
어드민 페이지에서 펀딩 등록 시 진열 페이지, 상세페이지 생성 연결을 위한 파일 생성(작업중)
> [ksmart46] 펀딩 관련 어드민, 사용자 페이지 수정

- ks46team04/src/main/java/ks46team04/admin/controller/PurchaseController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/CommonMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/PurchaseMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/PurchaseService.java
- ks46team04/src/main/resources/mapper/CommonMapper.xml
- ks46team04/src/main/resources/mapper/PurchaseMapper.xml
- ks46team04/src/main/resources/static/css/sb-admin-2.min.css
- ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_list.html
- ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_update.html
author: LBR
detail:매입 수정 view 진행중, 매입 등록 완료(그룹자동증가코드)
file:
ks46team04/src/main/java/ks46team04/admin/mapper/CommonMapper.java ks46team04/src/main/resources/mapper/CommonMapper.xml ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_list.html ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_update.html ks46team04/src/main/java/ks46team04/admin/controller/PurchaseController.java ks46team04/src/main/java/ks46team04/admin/mapper/PurchaseMapper.java ks46team04/src/main/resources/mapper/PurchaseMapper.xml ks46team04/src/main/java/ks46team04/admin/service/PurchaseService.java ks46team04/src/main/resources/static/css/sb-admin-2.min.css
> [ks46team4] 매입 수정 view 진행중

- ks46team04/src/main/java/ks46team04/common/controller/CommonController.java
- ks46team04/src/main/resources/static/css/sb-admin-2.min.css
- ks46team04/src/main/resources/templates/admin/funding/current_amount.html
- ks46team04/src/main/resources/templates/fragments/header2.html
author: KHJ
file:
CommonController.java,
current_amount.html,
header2.html,
sb-admin-2.min.css
detail:
일부 유실 내용 재커밋
> [ksmart46] 펀딩 관련 페이지 수정

- ks46team04/src/main/resources/templates/fragments/header2.html
author: KHJ
file: header2.html
detail: 펀딩 진열 페이지 경로 수정
> [ksmart46] header2.html 일부 경로 수정

- ks46team04/src/main/java/ks46team04/admin/controller/DonationController.java
- ks46team04/src/main/resources/mapper/DonationMapper.xml
- ks46team04/src/main/resources/templates/admin/donation/donationMonthPay_add.html
- ks46team04/src/main/resources/templates/admin/donation/donationMonthPay_list.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayDetail_add.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayDetail_list.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayDetail_modify.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayMethod_add.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayMethod_list.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayMethod_modify.html
- ks46team04/src/main/resources/templates/admin/donation/donationRefund_add.html
- ks46team04/src/main/resources/templates/admin/donation/donationRefund_list.html
- ks46team04/src/main/resources/templates/admin/donation/donationRefund_modify.html
- ks46team04/src/main/resources/templates/admin/donation/donationSub_add.html
- ks46team04/src/main/resources/templates/admin/donation/donationSub_list.html
- ks46team04/src/main/resources/templates/admin/donation/donation_add.html
- ks46team04/src/main/resources/templates/admin/donation/donation_list.html
- ks46team04/src/main/resources/templates/admin/donation/donation_modify.html
- ks46team04/src/main/resources/templates/admin/search/donation_search.html
author: 백지은
file: donation 컨트롤러, 서비스, 매퍼, HTML
detail: 정기기부 관련 파일 수정
> [ksmart46team04] 정기기부 관련 파일 수정

- ks46team04/src/main/java/ks46team04/admin/controller/PurchaseController.java
- ks46team04/src/main/java/ks46team04/admin/service/PurchaseService.java
- ks46team04/src/main/resources/static/css/lbr-style.css
- ks46team04/src/main/resources/static/css/sb-admin-2.min.css
- ks46team04/src/main/resources/templates/admin/purchase_sale/payment_vat_list.html
- ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_insert.html
- ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_list.html
author: LBR
detail: 삭제 view 진행 중
file:
ks46team04/src/main/resources/static/css/lbr-style.css ks46team04/src/main/resources/templates/admin/purchase_sale/payment_vat_list.html ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_insert.html ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_list.html ks46team04/src/main/java/ks46team04/admin/controller/PurchaseController.java ks46team04/src/main/java/ks46team04/admin/service/PurchaseService.java ks46team04/src/main/resources/static/css/sb-admin-2.min.css
> [ks46team4] insetPurchase 완료

- ks46team04/src/main/java/ks46team04/admin/controller/GoodsController.java
- ks46team04/src/main/java/ks46team04/admin/controller/StockController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/GoodsMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/StockMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/GoodsService.java
- ks46team04/src/main/java/ks46team04/admin/service/StockService.java
- ks46team04/src/main/resources/mapper/FoundationMapper.xml
- ks46team04/src/main/resources/mapper/GoodsMapper.xml
- ks46team04/src/main/resources/mapper/StockMapper.xml
- ks46team04/src/main/resources/static/css/admin_kgr9.css
- ks46team04/src/main/resources/static/js/custom/kgr9.js
- ks46team04/src/main/resources/templates/admin/foundation/modify_foundation_request.html
- ks46team04/src/main/resources/templates/admin/goods/add_goods.html
- ks46team04/src/main/resources/templates/admin/goods/goods_list.html
- ks46team04/src/main/resources/templates/admin/goods/modify_goods.html
- ks46team04/src/main/resources/templates/admin/stock/add_in_outcoming.html
- ks46team04/src/main/resources/templates/admin/stock/in_outcoming_list.html
- ks46team04/src/main/resources/templates/admin/stock/modify_in_outcoming.html
- ks46team04/src/main/resources/templates/admin/stock/modify_stock.html
author: 김귀림
file: goods_list.html, add_goods.html 등 관련 MVC 파일
detail: 상품 등록시 상품명 중복확인 기능 추가, 상품 조회 기능 추가 - DateRangePicker
> [ksmart46team04] 상품명 중복확인, 상품 조회 기능 추가

- ks46team04/src/main/java/ks46team04/admin/controller/PurchaseController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/CommonMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/PurchaseMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/PurchaseService.java
- ks46team04/src/main/resources/mapper/CommonMapper.xml
- ks46team04/src/main/resources/mapper/PurchaseMapper.xml
- ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_list.html
author: LBR
detail: 매입 삭제 진행 중, 매출 그룹 코드 추가
file:
ks46team04/src/main/java/ks46team04/admin/mapper/CommonMapper.java ks46team04/src/main/resources/mapper/CommonMapper.xml ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_list.html ks46team04/src/main/java/ks46team04/admin/controller/PurchaseController.java ks46team04/src/main/java/ks46team04/admin/mapper/PurchaseMapper.java ks46team04/src/main/resources/mapper/PurchaseMapper.xml ks46team04/src/main/java/ks46team04/admin/service/PurchaseService.java
> [ks46team4] 매입삭제 진행중

- ks46team04/src/main/java/ks46team04/admin/controller/UserController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/UserMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/UserService.java
- ks46team04/src/main/resources/mapper/UserMapper.xml
- ks46team04/src/main/resources/templates/admin/user/loginLog.html
- ks46team04/src/main/resources/templates/admin/user/userList.html
- ks46team04/src/main/resources/templates/admin/user/userSleepList.html
author: 김가람
file:
ks46team04/src/main/resources/templates/admin/user/loginLog.html ks46team04/src/main/java/ks46team04/admin/controller/UserController.java ks46team04/src/main/resources/templates/admin/user/userList.html ks46team04/src/main/java/ks46team04/admin/mapper/UserMapper.java ks46team04/src/main/resources/mapper/UserMapper.xml ks46team04/src/main/java/ks46team04/admin/service/UserService.java ks46team04/src/main/resources/templates/admin/user/userSleepList.html
> [ksmart46team04] 미접속일수 구현

- ks46team04/src/main/java/ks46team04/admin/controller/PurchaseController.java
- ks46team04/src/main/java/ks46team04/admin/dto/Purchase.java
- ks46team04/src/main/java/ks46team04/admin/mapper/PurchaseMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/ProfitLossService.java
- ks46team04/src/main/java/ks46team04/admin/service/PurchaseService.java
- ks46team04/src/main/java/ks46team04/scheduling/SettlementScheduling.java
- ks46team04/src/main/resources/mapper/ProfitLossMapper.xml
- ks46team04/src/main/resources/mapper/PurchaseMapper.xml
- ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_insert.html
- ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_list.html
- ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_update.html
author: LBR
detail:재무 진행 상황 주석 정리
file:
ks46team04/src/main/resources/mapper/ProfitLossMapper.xml ks46team04/src/main/java/ks46team04/admin/service/ProfitLossService.java ks46team04/src/main/java/ks46team04/admin/dto/Purchase.java ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_insert.html ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_list.html ks46team04/src/main/resources/templates/admin/purchase_sale/purchase_update.html ks46team04/src/main/java/ks46team04/admin/controller/PurchaseController.java ks46team04/src/main/java/ks46team04/admin/mapper/PurchaseMapper.java ks46team04/src/main/resources/mapper/PurchaseMapper.xml ks46team04/src/main/java/ks46team04/admin/service/PurchaseService.java …
> [ks46team4] 재무 개발 시작

- ks46team04/src/main/java/ks46team04/admin/controller/UserController.java
- ks46team04/src/main/java/ks46team04/admin/dto/User.java
- ks46team04/src/main/java/ks46team04/admin/mapper/UserMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/UserService.java
- ks46team04/src/main/resources/mapper/UserMapper.xml
- ks46team04/src/main/resources/templates/admin/search/search.html
- ks46team04/src/main/resources/templates/admin/user/activityStatus.html
- ks46team04/src/main/resources/templates/admin/user/loginLog.html
- ks46team04/src/main/resources/templates/admin/user/modifyUser.html
- ks46team04/src/main/resources/templates/admin/user/removeUser.html
- ks46team04/src/main/resources/templates/admin/user/userDropList.html
- ks46team04/src/main/resources/templates/admin/user/userLevel.html
- ks46team04/src/main/resources/templates/admin/user/userList.html
- ks46team04/src/main/resources/templates/admin/user/userSleepList.html
author: 김가람
file:
activityStatus.html
loginLog.html
modifyUser.html
removeUser.html
search.html
User.java
userDropList.html
userLevel.html
userList.html
UserMapper.xml
userSleepList.html
> [ksmart46team04] 회원 삭제

- ks46team04/src/main/java/ks46team04/admin/dto/User.java
- ks46team04/src/main/java/ks46team04/common/controller/CommonController.java
- ks46team04/src/main/java/ks46team04/user/controller/UserMainController.java
- ks46team04/src/main/resources/mapper/UserMapper.xml
- ks46team04/src/main/resources/static/css/sb-admin-2.min.css
- ks46team04/src/main/resources/templates/admin/user/addUser.html
- ks46team04/src/main/resources/templates/admin/user/modifyUser.html
- ks46team04/src/main/resources/templates/common/register.html
- ks46team04/src/main/resources/templates/user/myPage_drop.html
author: 김가람
file:
addUser.html
CommonController.java
modifyUser.html
myPage_drop.html
register.html
sb-admin-2.min.css
User.java
UserMapper.xml
> [ksmart46team04]유저 회원가입 및 탈퇴 초기세팅

- ks46team04/src/main/java/ks46team04/admin/controller/FoundationController.java
- ks46team04/src/main/java/ks46team04/admin/controller/GoodsController.java
- ks46team04/src/main/java/ks46team04/admin/dto/Goods.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FoundationMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/GoodsMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/StockMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/FoundationService.java
- ks46team04/src/main/java/ks46team04/admin/service/GoodsService.java
- ks46team04/src/main/resources/mapper/FoundationMapper.xml
- ks46team04/src/main/resources/mapper/GoodsMapper.xml
- ks46team04/src/main/resources/mapper/StockMapper.xml
- ks46team04/src/main/resources/static/js/custom/kgr9.js
- ks46team04/src/main/resources/templates/admin/foundation/add_foundation_request.html
- ks46team04/src/main/resources/templates/admin/foundation/foundation_request_list.html
- ks46team04/src/main/resources/templates/admin/foundation/modify_foundation_request.html
- ks46team04/src/main/resources/templates/admin/goods/add_goods.html
- ks46team04/src/main/resources/templates/admin/goods/goods_list.html
author: 김귀림
file: goods_list.html,remove_goods 관련 MVC 파일
detail: 상품 삭제 기능 추가 - 최종 재고량 0인 경우 상품 정보 삭제
> [ksmart46team04] 상품 삭제 기능 추가

- ks46team04/src/main/java/ks46team04/admin/controller/DonationController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/DonationMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/DonationService.java
- ks46team04/src/main/resources/mapper/DonationMapper.xml
- ks46team04/src/main/resources/templates/admin/donation/donationMonthPay_add.html
- ks46team04/src/main/resources/templates/admin/donation/donationMonthPay_list.html
- ks46team04/src/main/resources/templates/admin/donation/donationMonthPay_modify.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayDetail_add.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayDetail_list.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayDetail_modify.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayMethod_add.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayMethod_list.html
- ks46team04/src/main/resources/templates/admin/donation/donationPayMethod_modify.html
- ks46team04/src/main/resources/templates/admin/donation/donationRefund_add.html
- ks46team04/src/main/resources/templates/admin/donation/donationRefund_list.html
- ks46team04/src/main/resources/templates/admin/donation/donationRefund_modify.html
- ks46team04/src/main/resources/templates/admin/donation/donationSub_add.html
- ks46team04/src/main/resources/templates/admin/donation/donationSub_cancel.html
- ks46team04/src/main/resources/templates/admin/donation/donationSub_list.html
- ks46team04/src/main/resources/templates/admin/donation/donationSub_modify.html
- ks46team04/src/main/resources/templates/admin/donation/donation_add.html
- ks46team04/src/main/resources/templates/admin/donation/donation_list.html
- ks46team04/src/main/resources/templates/admin/donation/donation_modify.html
- ks46team04/src/main/resources/templates/common/donation/donation_cancel.html
- ks46team04/src/main/resources/templates/common/donation/donation_list.html
- ks46team04/src/main/resources/templates/common/donation/donation_modify.html
- ks46team04/src/main/resources/templates/fragments/aside.html
author: 백지은
file:
donation 관련 컨트롤러, 서비스, 매퍼, html,
aside.html
detail: 정기기부 부분/전체삭제 추가, aside 정기후원->정기기부 수정
> [ksmart46team04] 정기기부 부분/전체삭제 추가, aside 수정

- ks46team04/src/main/java/ks46team04/admin/controller/FoundationController.java
- ks46team04/src/main/java/ks46team04/admin/controller/GoodsController.java
- ks46team04/src/main/java/ks46team04/admin/dto/Foundation.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FoundationMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/StockMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/FoundationService.java
- ks46team04/src/main/java/ks46team04/admin/service/GoodsService.java
- ks46team04/src/main/resources/mapper/FoundationMapper.xml
- ks46team04/src/main/resources/mapper/GoodsMapper.xml
- ks46team04/src/main/resources/mapper/StockMapper.xml
- ks46team04/src/main/resources/static/css/admin_kgr9.css
- ks46team04/src/main/resources/static/js/custom/kgr9.js
- ks46team04/src/main/resources/templates/admin/foundation/add_foundation.html
- ks46team04/src/main/resources/templates/admin/foundation/foundation_list.html
- ks46team04/src/main/resources/templates/admin/foundation/modify_foundation.html
- ks46team04/src/main/resources/templates/admin/goods/goods_list.html
- ks46team04/src/main/resources/templates/fragments/aside.html
author: 김귀림
file: foundataion_list.html,add_foundation.html,modify_foundation.html, foundation 관련 MVC 파일, 개인 js 파일
detail: 재단 등록 - 재단명 중복확인, 카카오 주소 API
재단 조회 - DateRangePicker
재단 삭제 - 재단 요청사항 진행 중 없는 경우 삭제
> [ksmart46team04] 재단 등록,수정,삭제,조회 기능 추가

- ks46team04/src/main/java/ks46team04/admin/controller/UserController.java
- ks46team04/src/main/java/ks46team04/user/controller/UserMainController.java
- ks46team04/src/main/resources/templates/admin/user/modifyUser.html
- ks46team04/src/main/resources/templates/admin/user/removeUser.html
- ks46team04/src/main/resources/templates/user/myPage_drop.html
- ks46team04/src/main/resources/templates/user/myPage_myInfo.html
- ks46team04/src/main/resources/templates/user/myPage_myInfoModify.html
author: 김가람
file:
modifyUser.html
myPage_drop.html
myPage_myInfo.html
myPage_myInfoModify.html
removeUser.html
> [ksmart46team04] 마이페이지 초기셋팅

- ks46team04/src/main/java/ks46team04/user/controller/UserMainController.java
- ks46team04/src/main/resources/templates/user/myPage_myInfoModify.html
author: 김가람
file:
myPage_myInfoModify.html
> [ksmart46team04] 마이페이지 회원정보수정 초기셋팅

- ks46team04/src/main/java/ks46team04/admin/controller/FoundationController.java
- ks46team04/src/main/java/ks46team04/admin/controller/GoodsController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FoundationMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/FoundationService.java
- ks46team04/src/main/resources/mapper/FoundationMapper.xml
- ks46team04/src/main/resources/templates/admin/foundation/add_foundation.html
- ks46team04/src/main/resources/templates/admin/foundation/add_foundation_request.html
- ks46team04/src/main/resources/templates/admin/foundation/foundation_list.html
- ks46team04/src/main/resources/templates/admin/foundation/foundation_request_list.html
- ks46team04/src/main/resources/templates/admin/foundation/modify_foundation.html
- ks46team04/src/main/resources/templates/admin/foundation/modify_foundation_request.html
- ks46team04/src/main/resources/templates/admin/goods/add_goods.html
- ks46team04/src/main/resources/templates/admin/goods/goods_list.html
author: 김귀림
file: foundataion_request_list.html,add_foundataion_request.html,modify_foundataion_request.html, foundation 관련 MVC 파일
detail: 재단 삭제 - 요청사항 대기중, 진행중 없는 경우 삭제,
재단 요청사항 삭제 - 재단 요청사항 완료랑 진행중 없는 경우 삭제
> [ksmart46team04] 재단 삭제, 재단 요청사항 등록,수정,삭제 기능 수정

- ks46team04/src/main/java/ks46team04/admin/controller/DonationController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/DonationMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/DonationService.java
- ks46team04/src/main/resources/mapper/DonationMapper.xml
- ks46team04/src/main/resources/templates/admin/donation/donation_list.html
author: 백지은
file: donation 컨트롤러, 서비스, 매퍼, html
detail: 정기기부 기간검색 추가
> [ksmart46team04] 정기기부 기간검색 추가

- ks46team04/src/main/java/ks46team04/admin/controller/UserController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/UserMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/UserService.java
- ks46team04/src/main/resources/mapper/UserMapper.xml
- ks46team04/src/main/resources/templates/admin/user/loginLog.html
- ks46team04/src/main/resources/templates/common/register.html
author: 김가람
file:
loginLog.html
UserMapper.xml
register.html
> [ksmart46team04] 로그인기록 삭제

- ks46team04/src/main/resources/mapper/FundingMapper.xml
- ks46team04/src/main/resources/templates/admin/funding/current_amount.html
- ks46team04/src/main/resources/templates/admin/funding/detailFundingPay.html
- ks46team04/src/main/resources/templates/admin/funding/manage.html
- ks46team04/src/main/resources/templates/admin/funding/modifyFunding.html
- ks46team04/src/main/resources/templates/admin/funding/modifyFundingRefund.html
- ks46team04/src/main/resources/templates/admin/funding/payments.html
- ks46team04/src/main/resources/templates/admin/funding/refund.html
- ks46team04/src/main/resources/templates/admin/funding/register.html
author: KHJ
file:
current_amount.html,
detailFundingPay.html,
manage.html,
modifyFundingRefund.html,
payments.html,
refund.html,
register.html
detail: 화면구현 일부 수정
> [ksmart46 team4] 펀딩 관련 페이지 수정

- ks46team04/src/main/java/ks46team04/admin/controller/GoodsController.java
author: 김귀림
file: GoodsController.java, GoodsService.java,
FoundationController.java, FoundationService.java
detail: 비즈니스로직(searchMap mapping) controller -> service로 수정
> [ksmart46team04] 상품, 재단 조회 기능 controller, service 수정

- ks46team04/src/main/java/ks46team04/common/controller/CommonController.java
- ks46team04/src/main/java/ks46team04/user/controller/UserMainController.java
- ks46team04/src/main/resources/templates/fragments/aside2.html
author: 김가람
file:
aside2.html
CommonController.java
> [ksmart46team04] 경로 수정

- ks46team04/src/main/java/ks46team04/admin/mapper/DonationMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FundingMapper.java
- ks46team04/src/main/java/ks46team04/user/controller/UserMainController.java
- ks46team04/src/main/java/ks46team04/user/service/UserMainService.java
- ks46team04/src/main/resources/mapper/DonationMapper.xml
- ks46team04/src/main/resources/mapper/FundingMapper.xml
- ks46team04/src/main/resources/templates/fragments/aside2.html
- ks46team04/src/main/resources/templates/user/myPage_myAutoPm.html
- ks46team04/src/main/resources/templates/user/myPage_myDonation.html
- ks46team04/src/main/resources/templates/user/myPage_myFunding.html
author: 김가람
file:
aside2.html
DonationMapper.java
DonationMapper.xml
FundingMapper.java
FundingMapper.xml
myPage_myAutoPm.html
myPage_myDonation.html
myPage_myFunding.html
UserMainService.java
> [ksmart46team04] 마이페이지

- ks46team04/src/main/java/ks46team04/admin/controller/FoundationController.java
- ks46team04/src/main/java/ks46team04/admin/controller/GoodsController.java
- ks46team04/src/main/java/ks46team04/admin/controller/StockController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/StockMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/FoundationService.java
- ks46team04/src/main/java/ks46team04/admin/service/StockService.java
- ks46team04/src/main/resources/mapper/FoundationMapper.xml
- ks46team04/src/main/resources/mapper/StockMapper.xml
- ks46team04/src/main/resources/templates/admin/foundation/foundation_list.html
- ks46team04/src/main/resources/templates/admin/stock/stock_list.html
author: 김귀림
file: stock_list.html, stock 관련 MVC 파일
detail: 재고 검색 기능 추가
> [ksmart46team04] 재고 검색 기능 추가

- ks46team04/src/main/java/ks46team04/admin/controller/StockController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/StockMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/StockService.java
- ks46team04/src/main/resources/mapper/StockMapper.xml
- ks46team04/src/main/resources/templates/admin/stock/stock_list.html
- ks46team04/src/main/resources/templates/admin/stock/unusual_stock_detail_list.html
- ks46team04/src/main/resources/templates/fragments/aside.html
author: 김귀림
file: unusual_stock_detail_list.html, stock 관련 MVC 파일
detail: 비정상 재고 검색 기능 추가
> [ksmart46team04] 비정상 재고 검색 기능 추가

- ks46team04/src/main/resources/templates/admin/search/search.html
- ks46team04/src/main/resources/templates/admin/user/loginLog.html
- ks46team04/src/main/resources/templates/common/login.html
- ks46team04/src/main/resources/templates/fragments/header.html
- ks46team04/src/main/resources/templates/fragments/header3.html
author: 김가람
file:
header3.html
header.html
login.html
loginLog.html
search.html
> [ksmart46team04] 로그인창 관리자아이디 입력

- ks46team04/src/main/java/ks46team04/admin/controller/StockController.java
- ks46team04/src/main/java/ks46team04/admin/dto/InOutcoming.java
- ks46team04/src/main/java/ks46team04/admin/service/StockService.java
- ks46team04/src/main/resources/mapper/StockMapper.xml
- ks46team04/src/main/resources/templates/admin/stock/in_outcoming_list.html
author: 김귀림
file: in_outcoming_list.html, stock 관련 MVC 파일
detail: 입출고 검색 기능 추가
> [ksmart46team04] 입출고 검색 기능 추가

- ks46team04/src/main/resources/templates/common/login.html
> [ksmart46team04] 로그인 admin/user 타입

- ks46team04/src/main/java/ks46team04/admin/controller/UserController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/UserMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/UserService.java
- ks46team04/src/main/resources/mapper/UserMapper.xml
- ks46team04/src/main/resources/templates/admin/user/loginLog.html
- ks46team04/src/main/resources/templates/admin/user/userDetailList.html
- ks46team04/src/main/resources/templates/admin/user/userLevel.html
- ks46team04/src/main/resources/templates/admin/user/userList.html
- ks46team04/src/main/resources/templates/common/login.html
- ks46team04/src/main/resources/templates/user/myPage_myDonation.html
- ks46team04/src/main/resources/templates/user/myPage_myFunding.html
- ks46team04/src/main/resources/templates/user/myPage_myInfo.html
- ks46team04/src/main/resources/templates/user/myPage_myPayment.html
author: 김가람
file:
login.html
loginLog.html
myPage_myDonation.html
myPage_myFunding.html
myPage_myInfo.html
myPage_myPayment.html
userDetailList.html
userLevel.html
userList.html
UserMapper.xml
> [ksmart46team04] 로그인 user타입 아이디 변경

- ks46team04/src/main/java/ks46team04/admin/controller/GoodsController.java
- ks46team04/src/main/java/ks46team04/admin/controller/StockController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/GoodsMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/GoodsService.java
- ks46team04/src/main/java/ks46team04/admin/service/StockService.java
- ks46team04/src/main/resources/mapper/FoundationMapper.xml
- ks46team04/src/main/resources/mapper/GoodsMapper.xml
- ks46team04/src/main/resources/static/css/admin_kgr9.css
- ks46team04/src/main/resources/templates/admin/foundation/foundation_list.html
- ks46team04/src/main/resources/templates/admin/foundation/foundation_request_list.html
- ks46team04/src/main/resources/templates/admin/foundation/modify_foundation.html
- ks46team04/src/main/resources/templates/admin/foundation/modify_foundation_request.html
- ks46team04/src/main/resources/templates/admin/goods/add_goods.html
- ks46team04/src/main/resources/templates/admin/goods/goods_list.html
- ks46team04/src/main/resources/templates/admin/goods/modify_goods.html
- ks46team04/src/main/resources/templates/admin/stock/add_in_outcoming.html
- ks46team04/src/main/resources/templates/admin/stock/in_outcoming_list.html
- ks46team04/src/main/resources/templates/admin/stock/modify_in_outcoming.html
- ks46team04/src/main/resources/templates/admin/stock/modify_stock.html
- ks46team04/src/main/resources/templates/admin/stock/stock_list.html
- ks46team04/src/main/resources/templates/admin/stock/unusual_stock_detail_list.html
- ks46team04/src/main/resources/templates/fragments/aside.html
author: 김귀림
file: goods_list.html, goods 관련 MVC 파일
detail: goods 검색 조회 ajax 코드 수정
> [ksmart46team04] goods 검색 조회 ajax 코드 수정

- ks46team04/src/main/java/ks46team04/admin/controller/FoundationController.java
- ks46team04/src/main/java/ks46team04/admin/controller/StockController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FoundationMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/StockMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/FoundationService.java
- ks46team04/src/main/java/ks46team04/admin/service/StockService.java
- ks46team04/src/main/resources/mapper/FoundationMapper.xml
- ks46team04/src/main/resources/mapper/StockMapper.xml
- ks46team04/src/main/resources/templates/admin/foundation/add_foundation.html
- ks46team04/src/main/resources/templates/admin/foundation/add_foundation_request.html
- ks46team04/src/main/resources/templates/admin/foundation/foundation_list.html
- ks46team04/src/main/resources/templates/admin/foundation/foundation_request_list.html
- ks46team04/src/main/resources/templates/admin/foundation/modify_foundation.html
- ks46team04/src/main/resources/templates/admin/foundation/modify_foundation_request.html
- ks46team04/src/main/resources/templates/admin/goods/goods_list.html
- ks46team04/src/main/resources/templates/admin/stock/add_in_outcoming.html
- ks46team04/src/main/resources/templates/admin/stock/in_outcoming_list.html
- ks46team04/src/main/resources/templates/admin/stock/modify_in_outcoming.html
- ks46team04/src/main/resources/templates/admin/stock/stock_list.html
- ks46team04/src/main/resources/templates/admin/stock/unusual_stock_detail_list.html
author: 김귀림
file: foundation_list.html, foundation_request_list.html, stock_list.html, in_outcoming_list.html, unusual_stock_detail_list.html, foundation & stock 관련 MVC 파일
detail: foundation, foundation_request, stock, in_outcoming, unusual_stock 검색 조회 ajax 코드 수정
> [ksmart46team04] 재단, 재단 요청사항, 재고 관련 검색 조회 ajax 코드 수정

- ks46team04/src/main/java/ks46team04/admin/controller/UserController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/UserMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/UserService.java
- ks46team04/src/main/resources/mapper/UserMapper.xml
- ks46team04/src/main/resources/templates/admin/user/userDropList.html
- ks46team04/src/main/resources/templates/fragments/header2.html
- ks46team04/src/main/resources/templates/fragments/header3.html
- ks46team04/src/main/resources/templates/user/myPage_drop.html
- ks46team04/src/main/resources/templates/user/myPage_myInfo.html
author: 김가람
file:
header2.html
header3.html
myPage_drop.html
myPage_myInfo.html
userDropList.html
UserMapper.xml
> [ksmart46team04] 헤더 및 탈퇴회원리스트 수정

- ks46team04/src/main/java/ks46team04/admin/controller/FundingController.java
- ks46team04/src/main/resources/templates/admin/funding/modifyFunding.html
- ks46team04/src/main/resources/templates/admin/funding/register.html
author: KHJ
file:
register.html
detail: 펀딩 등록 페이지 - 등록아이디 표시, 펀딩 수정 화면 - 수정자 아이디 표시
> [ksmart46 team4] 어드민-펀딩 세션아이디 표시

- ks46team04/src/main/java/ks46team04/admin/controller/FoundationController.java
- ks46team04/src/main/java/ks46team04/admin/controller/GoodsController.java
- ks46team04/src/main/java/ks46team04/admin/controller/StockController.java
- ks46team04/src/main/java/ks46team04/admin/dto/Foundation.java
- ks46team04/src/main/java/ks46team04/admin/dto/Goods.java
- ks46team04/src/main/java/ks46team04/admin/dto/InOutcomingForm.java
- ks46team04/src/main/java/ks46team04/admin/dto/Stock.java
- ks46team04/src/main/java/ks46team04/admin/mapper/FoundationMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/GoodsMapper.java
- ks46team04/src/main/java/ks46team04/admin/mapper/StockMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/GoodsService.java
- ks46team04/src/main/java/ks46team04/admin/service/StockService.java
- ks46team04/src/main/resources/mapper/FoundationMapper.xml
- ks46team04/src/main/resources/mapper/GoodsMapper.xml
- ks46team04/src/main/resources/mapper/StockMapper.xml
- ks46team04/src/main/resources/templates/admin/goods/add_goods.html
- ks46team04/src/main/resources/templates/admin/goods/modify_goods.html
- ks46team04/src/main/resources/templates/admin/stock/add_in_outcoming.html
- ks46team04/src/main/resources/templates/admin/stock/add_unusual_stock_detail.html
- ks46team04/src/main/resources/templates/admin/stock/stock_list.html
author: 김귀림
file: add_in_outcoming.html, stock 관련 MVC 파일
detail: 상품 입출고 등록 시 입출고 이력,상품 재고, 상품 출고상세 자동 등록
(상품 재고 - 기존 재고인 경우 수량 업데이트/새로운 상품 입고인 경우 재고 등록,
상품 출고 상세 - 상품 출고인 경우 등록)
> [ksmart46team04] 상품 입출고 등록 기능 추가

- ks46team04/src/main/java/ks46team04/admin/controller/StockController.java
- ks46team04/src/main/java/ks46team04/admin/dto/InOutcoming.java
- ks46team04/src/main/java/ks46team04/admin/dto/InOutcomingForm.java
- ks46team04/src/main/java/ks46team04/admin/mapper/StockMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/StockService.java
- ks46team04/src/main/resources/mapper/StockMapper.xml
- ks46team04/src/main/resources/templates/admin/stock/add_in_outcoming.html
- ks46team04/src/main/resources/templates/admin/stock/in_outcoming_list.html
- ks46team04/src/main/resources/templates/admin/stock/modify_in_outcoming.html
author: 김귀림
file: modify_in_outcoming.html, StockController.java, StockMapper.java, StockService.java, StockMapper.xml
detail: 상품 입출고 정보 수정
> [ksmart46team04] 상품 입출고 수정 기능 추가

- ks46team04/src/main/java/ks46team04/admin/controller/StockController.java
- ks46team04/src/main/java/ks46team04/admin/mapper/StockMapper.java
- ks46team04/src/main/java/ks46team04/admin/service/StockService.java
- ks46team04/src/main/resources/mapper/StockMapper.xml
- ks46team04/src/main/resources/templates/admin/stock/add_in_outcoming.html
- ks46team04/src/main/resources/templates/admin/stock/in_outcoming_list.html
author: 김귀림
file: in_outcoming_list.html, StockController.java, StockMapper.java, StockService.java, StockMapper.xml
detail: 상품 입출고 조회, 체크박스 선택 삭제 기능 추가, 입출고 정보 삭제 시 재고 수량 자동 차감 및 출고 상세 정보 자동 삭제
> [ksmart46team04] 상품 입출고 조회, 체크박스 선택 삭제 기능 추가

- ks46team04/src/main/java/ks46team04/admin/controller/FoundationController.java
- ks46team04/src/main/java/ks46team04/admin/controller/GoodsController.java
- ks46team04/src/main/java/ks46team04/admin/controller/StockController.java
- ks46team04/src/main/java/ks46team04/admin/service/FoundationService.java
- ks46team04/src/main/java/ks46team04/admin/service/GoodsService.java
- ks46team04/src/main/resources/mapper/FoundationMapper.xml
- ks46team04/src/main/resources/mapper/GoodsMapper.xml
- ks46team04/src/main/resources/templates/admin/foundation/add_foundation_request.html
- ks46team04/src/main/resources/templates/admin/foundation/foundation_list.html
- ks46team04/src/main/resources/templates/admin/foundation/foundation_request_list.html
- ks46team04/src/main/resources/templates/admin/foundation/modify_foundation_request.html
- ks46team04/src/main/resources/templates/admin/goods/add_goods.html
- ks46team04/src/main/resources/templates/admin/goods/goods_list.html
- ks46team04/src/main/resources/templates/admin/goods/modify_goods.html
- ks46team04/src/main/resources/templates/admin/stock/add_in_outcoming.html
- ks46team04/src/main/resources/templates/admin/stock/in_outcoming_list.html
- ks46team04/src/main/resources/templates/fragments/aside.html
author: 김귀림
file: add_foundation_request.html, add_foundation_request.html, foundation_list.html, foundation_request_list.html, modify_foundation_request.html, add_goods.html, goods_list.html, modify_goods.html, add_in_outcoming.html, in_outcoming_list.html, aside.html, FoundationController.java, GoodsController.java, StockController.java, FoundationService.java, GoodsService.java, FoundationMapper.xml, GoodsMapper.xml
detail: 상품명/재단명 input -> select box로 수정, PK 생성 코드 수정 (사용자정의함수 -> Mapper 호출하여 기본 키 생성)
> [ksmart46team04] 상품명/재단명 select box 수정, PK 생성 코드 수정

- ks46team04/src/main/java/ks46team04/admin/controller/StockController.java
author: 김귀림
file:GoodsController.java,StockController.java,Stock.java,UnusualStock.java, StockMapper.java,GoodsService.java,StockService.java,StockMapper.xml,add_foundation_request.html,add_in_outcoming.html,add_unusual_stock_detail.html,in_outcoming_list.html,modify_stocktaking.html,stock_list.html,unusual_stock_detail_list.html detail: 입출고/출고상세/재고/비정상재고 등록/수정/삭제/조회 기능 추가, 상품 삭제 시 상품의 모든 입출고 정보, 재고, 비정상재고 자동삭제 기능 추가(해당 상품 재고의 최종재고수량이 모두 0인 경우 상품 정보 삭제), 재고 삭제 시 해당 재고의 모든 입출고 정보 삭제(해당 상품 재고의 최종재고 수량이 0인 경우 삭제)
> [ksmart46team04] 입출고/출고상세/재고/비정상재고 등록/수정/삭제/조회 기능 추가

- ks46team04/src/main/java/ks46team04/admin/service/FoundationService.java
- ks46team04/src/main/resources/templates/admin/stock/stock_list.html
author: 김귀림
file: FoundationService.jave, stock_list.html
detail: 재단 요청사항 pk 생성 코드 오타 수정, 재고 삭제 알림창 문구 수정
> [ksmart46team04]재단 요청사항 pk 생성 오타 수정, 재고 삭제 알림창 문구 수정

- ks46team04/src/main/resources/templates/common/funding_index.html
author: 김귀림
file: funding_index.html
detail:마스터 배포용 홈 메인 편집
> [ksmart46team04]마스터 배포용 홈 메인 편집

- ks46team04/src/main/resources/templates/admin/stock/modify_in_outcoming.html
- ks46team04/src/main/resources/templates/admin/stock/modify_unusual_stock_detail.html
author: 김귀림
file: modify_in_outcoming.html, modify_unusual_stock_detail.html
detail: 입출고 수정 페이지, 비정상재고 수정 페이지 수정하기 버튼, 돌아가기 버튼 오타 수정
> [ksmart46team04]입출고 수정 페이지, 비정상재고 수정 페이지 버튼 오타 수정
